# ah
name: Sylbot

# basic
verbose: false
silent: false

# input
data: ['items.csv']

# output
stub: items
overwrite: false
backup: true

# sql
hostname: 127.0.0.1
database: tpzdb
username: root
password: wolfkin
fail: true

# broker
restock: 3600
tick: 271433

# scrub
itemids: []
stock01: 5
stock12: 5
urls: []
